import = [ "/usr/lib/node_modules/alacritty-themes/themes/XTerm.toml" ]

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15
